---

# Stop firewall
- name: Stop firewall service on ubuntu 
  hosts: all
  tasks:
    - name: Stop ufw on ubuntu
      service:
        name: ufw
        state: stopped
        enabled: no
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


# Install Nagios
- hosts: nagios
  tasks:
    - name: Install and Configure Nagios on Ubuntu
      include_role:
        name: ubuntu-Nagios
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 


# Install Grafana
- hosts: grafana
  tasks:
    - name: Install and Configure Grafana on Ubuntu
      include_role:
        name: ubuntu-Grafana
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 


# Install Prometheus
- hosts: prometheus
  tasks:
    - name: Install and Configure Prometheus on Ubuntu
      include_role:
        name: ubuntu-Prometheus
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 


# Install Influxdb
- hosts: influxdb
  tasks:
    - name: Install and Configure InfluxDB on Ubuntu
      include_role:
        name: ubuntu-Influxdb
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 

# Install Httpd and PHP
- hosts: httpd_php
  tasks:
    - name: Install Apache2 and PHP on Ubuntu
      include_role:
        name: ubuntu-Apache2_php
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'



# Install Mariadb
- hosts: mariadb
  tasks:
    - name: Install MariaDB on Ubuntu
      include_role:
        name: ubuntu-Mariadb
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


# Install and Configure Elastic Stack (Elasticsearch, Kibana and Logstash) on Ubuntu
- hosts: elasticsearch
  tasks:
    - name: Install and Configure Elasticsearch on Ubuntu
      include_role:  
        name: ubuntu-Elasticsearch
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- hosts: kibana
  tasks:
    - name: Install and Configure Kibana on Ubuntu
      include_role:  
        name: ubuntu-Kibana
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


 
- hosts: logstash
  tasks:
    - name: Install and Configure Logstash on Ubuntu
      include_role:  
        name: ubuntu-Logstash
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

 
