---
# tasks file for ubuntu-Influxdb



- name: add influxdb repo in /etc/apt/sources.list.d/influxdb.list
  copy:
    dest: /etc/apt/sources.list.d/influxdb.list
    content: deb https://repos.influxdata.com/ubuntu focal stable

- name: Get InfluxData repo using apt-key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Install influxdb using apt
  apt:
    name: influxdb
    state: present
    update_cache: yes

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install influxdb using pip # To enable to execute influxdb_database in ansible
  pip:
    name: influxdb

- name: Start and Enable InfluxDB
  systemd:
    name: influxdb
    state: started
    enabled: yes

- name: Enable http authentication
  copy:
    dest: /etc/influxdb/influxdb.conf
    content: |
      [http]
      auth-enabled = true 

# Optional
#- name: Create database
#  influxdb_database:
#    hostname: "qjkvcombo"
#    username: "combo"
#    password: "0000"
#    database_name: "ubuntu-influxdb"
#    state: present
